# Generated by Django 5.0.6 on 2024-08-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_checked_in', models.DateField()),
                ('date_checked_out', models.DateField()),
                ('booking_status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('CheckedOut', 'CheckedOut')], max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('dated', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('emergency_name', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('emergency_tel', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('has_paid', models.BooleanField(default=False)),
                ('has_fully_paid', models.BooleanField(default=False)),
                ('is_booked', models.BooleanField(default=False)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='guests/')),
            ],
        ),
        migrations.CreateModel(
            name='GuestEmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=10)),
                ('relationship', models.CharField(choices=[('Spouse', 'Spouse'), ('Friend', 'Friend'), ('Parent', 'Parent'), ('Other', 'Other')], max_length=100)),
                ('other', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('initial_payment', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('final_payment', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('payment_method', models.CharField(choices=[('Virtual', 'Virtual'), ('Cash', 'Cash')], default='Cash', max_length=100)),
                ('payment_verified', models.BooleanField(default=False)),
                ('payment_status', models.CharField(choices=[('Fully-Paid', 'Fully-Paid'), ('Pending', 'Pending'), ('Failed', 'Failed'), ('Part-Payment', 'Part-Payment')], default='Fully-Paid', max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=100, unique=True)),
                ('room_type', models.CharField(choices=[('Double-sized', 'Double-sized'), ('Queen-sized', 'Queen-sized')], max_length=100)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Maintenance', 'Maintenance')], max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
