from django.urls import path
from .views import *

urlpatterns = [ 
    path("rooms/", RoomListCreateAPIView.as_view()),
    path("rooms/delete/<int:pk>/", RoomDestroyAPIview.as_view()),
    path("rooms/search/<str:lookup_value>/", SearchRoomAPIView.as_view()),
    path("rooms/edit/<int:pk>/", RoomUpdateAPIView.as_view()),
    path("rooms/totalRoomsAvailable/", TotalRoomsAvailableAPIView.as_view()),
    path("guests/", GuestListCreateAPIView.as_view()),
    path("guests/search/<str:lookup_value>/", SearchGuestAPIView.as_view()),
    path("guests/totalGuest/", TotalNumberOfGuestAPIView.as_view()),
    path("guests/<int:pk>/", GuestUpdateAPIView.as_view()),
    path("guests/delete/<int:pk>/", GuestDestroyAPIView.as_view()),
    path("guests/debtors/", ClientInDebtAPIView.as_view()),
    path("bookings/", BookingListAPIView.as_view()),
    path("bookings/create/", BookingCreateAPIView.as_view()),
    path("bookings/search/<str:lookup_value>", BookingSearchAPIView.as_view()),
    path("bookings/search/<int:pk>/", BookingSearchByID.as_view()),
    path("bookings/<int:pk>", BookingDeleteAPIView.as_view()),
    path("bookings/totalBookings/", TotalBookingAPIView.as_view()),
    path("booking/bookungTrends/", BookingTrendingView.as_view()),
    path("booking/upcomingBooking/<str:date>/", UpComingBookingAPIView.as_view()),
    path("bookings/main/", BookingMainListCreateAPIView.as_view()),
    path('payment/list/', PaymentAPIView.as_view()),
    path('payment/debtors/list/', ClientInDebtAPIView.as_view()),
    path('payment/search/<str:lookup_value>/', SearchPaymentAPIView.as_view()),
    path('payment/<int:pk>/', PaymentUpdateDestroyAPIView.as_view()),
    path('payment/totalIncome/', TotalIncomeAPIView.as_view()),
    path('payment/create/', PaymentCreateAPIView.as_view()),
    path('guest/try_create/', GuestCreateGenericAPIView.as_view()),
    path('reports/bookingsReport/', BookingsReport.as_view()),
    path("reports/bookings/no-filter/", BookingReportNoFilters.as_view()),
    path("reports/payment/no-filter/", PaymentReportNoFilters.as_view()),
    path('reports/paymentsReport/', PaymentsReport.as_view()),
]